version: '3.8'

services:
  web:
    build: ./site
    ports:
      - "80:80"
    restart: always

  zap:
    image: ghcr.io/zaproxy/zaproxy:latest
    volumes:
      - ./zap-reports:/zap/wrk
    command: >
      zap.sh -daemon -host 0.0.0.0 -port 8080
    ports:
      - "8080:8080"
    restart: always
