version: '3.8'

services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:latest
    volumes:
      - ./zap-reports:/zap/wrk
    command: >
      zap-baseline.py
      -t https://test.soundstorm.pp.ua
      -r /zap/wrk/zap_report.html
      -I
