name: Security Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare output directory
        run: mkdir -p zap_output

      - name: Run OWASP ZAP Baseline Scan
        run: |
          docker run --rm -u $(id -u):$(id -g) \
            -e HOME=/zap/wrk \
            -v $(pwd)/zap_output:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t https://test.soundstorm.pp.ua \
            -r zap_report.html \
            -J zap_report.json \
            -z "-config api.disablekey=true" || true

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_output/*
